"""
notes.py — Sage Structure Specialist (Notion MCP Integration)

Uses NotionMCP for real Notion workspace integration.
"""

import asyncio
import uuid
import logging

logger = logging.getLogger("nexus")

from nexus.models.schemas import AgentResult, SuggestionChip
from nexus.agents.base import BaseAgent
from nexus.agents.blackboard import Blackboard
from nexus.config import get_demo_mode

_DEMO = get_demo_mode()


class SageAgent(BaseAgent):
    """
    NEXUS Structure Specialist (Sage)
    Knowledge architecture, Notion sync, strategy roadmaps.
    Uses NotionMCP for real Notion workspace integration.
    """

    def __init__(self, blackboard: Blackboard):
        super().__init__(name="sage", blackboard=blackboard)

    async def think(self, prompt: str) -> AgentResult:
        """Structure and persist knowledge artifacts."""
        self.trace("Mapping topic dependencies for the knowledge vault")

        research_latest = self.get_state("research.latest")

        if research_latest:
            self.trace(
                f"Structuring research findings for: {research_latest['query']}",
                status="running",
            )

        self.trace("Connecting to Notion Knowledge Base", status="running")

        notion_page_id = None
        if not _DEMO:
            try:
                from nexus.mcp_servers.notion_mcp import NotionMCP

                notion = NotionMCP(demo_mode=False)
                title = f"NEXUS: {research_latest.get('query', 'Session') if research_latest else 'Quick Note'}"
                notion_page_id = await notion.create_page(
                    title, "Generated by NEXUS Swarm"
                )
            except Exception as e:
                logger.warning(f"Sage Notion MCP failed: {e}")

        doc_id = f"sage_{uuid.uuid4().hex[:6]}"

        if notion_page_id:
            self.trace(f"Synced to Notion: {notion_page_id}", status="done")
        else:
            self.trace(f"Synchronizing session artifact: {doc_id}", status="done")

        await asyncio.sleep(0.3)

        notion_section = ""
        if notion_page_id:
            notion_section = f"- **Notion Link**: [View in Notion](https://notion.so/{notion_page_id.replace('-', '')})"
        else:
            notion_section = "- **Notion**: Demo mode (use API key for live sync)"

        summary = f"Knowledge artifact '{doc_id}' created and tiered in the vault."
        markdown = f"""# Sage Strategic Asset: Knowledge Mapping

Sage has structured your session into a permanent, searchable asset.

### Knowledge Architecture
- **Topic**: {research_latest["query"] if research_latest else "General Focus"}
- **Artifact ID**: `{doc_id}`
- **Tier**: Layer 3 (Strategic/Long-term)

### Strategy Roadmap
- [x] Initial Context Capture
- [ ] Multi-platform Sync (Notion/Drive)
- [ ] Weekly Recursive Review

{notion_section}

---
*Sage (Structure Specialist)*
        """

        suggestions = [
            SuggestionChip(
                label="Export to PDF",
                prompt="Sage, export this mission report to a PDF",
            ),
            SuggestionChip(
                label="Link to Projects",
                prompt="Sage, connect this note to my '2026 Vision' workspace",
            ),
        ]

        self.set_state("sage.latest_asset", doc_id)
        self.set_state("sage.notion_id", notion_page_id)

        self.trace("Strategic knowledge layering complete", status="done")

        return self.create_result(
            summary=summary, markdown=markdown, suggestions=suggestions, confidence=0.99
        )
